from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
import os
import glob

import numpy as np
import torch
from PIL import Image
import random

# Import VAE directly from local file to avoid importing aerial_gym (isaacgym)
from importlib.util import spec_from_file_location, module_from_spec

_vae_path = Path(__file__).with_name("VAE.py")
_spec = spec_from_file_location("VAE_local", str(_vae_path))
_mod = module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(_mod)
VAE = _mod.VAE


def load_index(index_csv, split) -> None:
    rows = []
    with open(index_csv, "r") as f:
        reader = csv.DictReader(f)
        for r in reader:
            if r["split"] == split:
                rows.append(r)
    return rows


def read_image_gray(path, resize_wh, pil_interp=Image.BILINEAR) -> None:
    img = Image.open(path).convert("L").resize(resize_wh, pil_interp)
    arr = np.asarray(img, dtype=np.float32) / 255.0
    t = torch.from_numpy(arr)[None, ...]  # [1,H,W]
    return t


def clean_state_dict(state_dict) -> None:
    clean = {}
    for k, v in state_dict.items():
        if k.startswith("module."):
            k = k.replace("module.", "")
        if k.startswith("dronet."):
            k = k.replace("dronet.", "encoder.")
        clean[k] = v
    return clean


def save_pair(orig_t, recon_t, out_path) -> None:
    # orig_t, recon_t: [1,H,W] in [0,1]
    H, W = orig_t.shape[-2:]
    canvas = Image.new("L", (W * 2, H))
    o = Image.fromarray((orig_t.squeeze().cpu().numpy() * 255).astype(np.uint8))
    r = Image.fromarray((recon_t.squeeze().cpu().numpy() * 255).astype(np.uint8))
    canvas.paste(o, (0, 0))
    canvas.paste(r, (W, 0))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(out_path)


def save_dual_pair(orig_bi, recon_bi, orig_ne, recon_ne, out_path) -> None:
    # All tensors are [1,H,W] in [0,1]
    H, W = orig_bi.shape[-2:]
    canvas = Image.new("L", (W * 4, H))
    # Bilinear pair (left half)
    o_bi = Image.fromarray((orig_bi.squeeze().cpu().numpy() * 255).astype(np.uint8))
    r_bi = Image.fromarray((recon_bi.squeeze().cpu().numpy() * 255).astype(np.uint8))
    canvas.paste(o_bi, (0, 0))
    canvas.paste(r_bi, (W, 0))
    # Nearest pair (right half)
    o_ne = Image.fromarray((orig_ne.squeeze().cpu().numpy() * 255).astype(np.uint8))
    r_ne = Image.fromarray((recon_ne.squeeze().cpu().numpy() * 255).astype(np.uint8))
    canvas.paste(o_ne, (2 * W, 0))
    canvas.paste(r_ne, (3 * W, 0))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(out_path)


def save_single(t, out_path) -> None:
    img = Image.fromarray((t.squeeze().cpu().numpy() * 255).astype(np.uint8))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_path)


def save_grid(pairs, out_path, ncols=8) -> None:
    if not pairs:
        return
    H, W = pairs[0][0].shape[-2:]
    cell_w = W * 2
    n = len(pairs)
    ncols = min(ncols, n)
    nrows = math.ceil(n / ncols)
    grid = Image.new("L", (cell_w * ncols, H * nrows))
    for idx, (orig, recon) in enumerate(pairs):
        r = idx // ncols
        c = idx % ncols
        x0 = c * cell_w
        y0 = r * H
        o = Image.fromarray((orig.squeeze().cpu().numpy() * 255).astype(np.uint8))
        rc = Image.fromarray((recon.squeeze().cpu().numpy() * 255).astype(np.uint8))
        grid.paste(o, (x0, y0))
        grid.paste(rc, (x0 + W, y0))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    grid.save(out_path)


def main() -> None:
    p = argparse.ArgumentParser(description="Reconstruct static-camera depth images with VAE and save side-by-side pairs.")
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument("--images_glob", type=str, nargs="+", help="One or more glob patterns for input images (PNG/JPG)")
    src.add_argument("--index_csv", type=str, help="CSV generated by extract_static_vae_frames.py")
    p.add_argument("--split", type=str, default="val", choices=["train","val","test"], help="Used only with --index_csv")
    p.add_argument("--weights", type=str, required=True, help="Path to VAE weights .pth")
    p.add_argument("--latent_dims", type=int, default=-1, help="Latent size; if -1, auto-detect from checkpoint")
    p.add_argument("--image_w", type=int, default=480)
    p.add_argument("--image_h", type=int, default=270)
    p.add_argument("--num_random", type=int, default=100, help="Random subset size")
    p.add_argument("--seed", type=int, default=17)
    p.add_argument("--out_dir", type=str, default="aerial_gym/utils/vae/val_reports/recon")
    p.add_argument("--device", type=str, default="cuda:0")
    p.add_argument("--grid", action="store_true", help="Also save a grid image of the first N pairs")
    args = p.parse_args()

    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    resize_wh = (args.image_w, args.image_h)

    # Collect file list
    img_paths = []
    if args.index_csv:
        rows = load_index(args.index_csv, args.split)
        img_paths = [Path(r["image_path"]) for r in rows]
    else:
        for g in args.images_glob:
            # Support absolute and relative glob patterns
            if os.path.isabs(g):
                matches = glob.glob(g)
                img_paths.extend(sorted(Path(p) for p in matches))
            else:
                img_paths.extend(sorted(Path().glob(g)))

    # Randomly sample requested number of images
    if args.num_random is not None and len(img_paths) > args.num_random:
        rng = random.Random(args.seed)
        img_paths = rng.sample(img_paths, args.num_random)
    if not img_paths:
        print("No images found.")
        return

    # Load checkpoint and auto-detect latent size if needed
    state_obj = torch.load(args.weights, map_location="cpu")
    state = clean_state_dict(state_obj.state_dict() if hasattr(state_obj, "state_dict") else state_obj)
    detected_latent = None
    # Try encoder dense1 first (shape [2*L, 512])
    for k in ("encoder.dense1.weight", "dronet.dense1.weight"):
        if k in state:
            w = state[k]
            detected_latent = int(w.shape[0] // 2)
            break
    # Fallback: decoder dense (shape [512, L])
    if detected_latent is None and "img_decoder.dense.weight" in state:
        w = state["img_decoder.dense.weight"]
        detected_latent = int(w.shape[1])
    latent_dims = args.latent_dims if args.latent_dims > 0 else (detected_latent or 64)
    if detected_latent is not None and args.latent_dims > 0 and args.latent_dims != detected_latent:
        print(f"[INFO] Overriding latent_dims={args.latent_dims} with detected={detected_latent} from checkpoint")
        latent_dims = detected_latent

    # Model
    vae = VAE(input_dim=1, latent_dim=latent_dims, inference_mode=True).to(device)
    vae.load_state_dict(state)
    vae.eval()

    out_root = Path(args.out_dir)
    # Create a unique subfolder for this run
    sub = f"subset_{len(img_paths)}_seed{args.seed}"
    out_root = out_root / sub
    pairs_for_grid = []
    with torch.no_grad():
        for pth in img_paths:
            # Load with bilinear and nearest for side-by-side comparison
            t_bi = read_image_gray(pth, resize_wh, Image.BILINEAR).to(device)  # [1,H,W]
            t_ne = read_image_gray(pth, resize_wh, Image.NEAREST).to(device)   # [1,H,W]

            # Reconstruct bilinear
            t_bi_bchw = t_bi.unsqueeze(0)  # [1,1,H,W]
            recon_bi, mu_bi, logvar_bi, z_bi = vae.forward(t_bi_bchw)
            recon_bi = recon_bi.squeeze(0)  # [1,H,W]

            # Reconstruct nearest
            t_ne_bchw = t_ne.unsqueeze(0)
            recon_ne, mu_ne, logvar_ne, z_ne = vae.forward(t_ne_bchw)
            recon_ne = recon_ne.squeeze(0)

            # Save dual side-by-side: [orig_bi | recon_bi | orig_ne | recon_ne]
            base = pth.stem
            dual_pair_file = out_root / f"{base}_pair_bilinear_vs_nearest.png"
            save_dual_pair(t_bi.cpu(), recon_bi.cpu(), t_ne.cpu(), recon_ne.cpu(), dual_pair_file)
            # Also save individual pairs if needed
            pair_bi_file = out_root / f"{base}_pair_bilinear.png"
            pair_ne_file = out_root / f"{base}_pair_nearest.png"
            save_pair(t_bi.cpu(), recon_bi.cpu(), pair_bi_file)
            save_pair(t_ne.cpu(), recon_ne.cpu(), pair_ne_file)
            if len(pairs_for_grid) < 64:
                pairs_for_grid.append((t_bi.cpu(), recon_bi.cpu()))

    if args.grid and pairs_for_grid:
        save_grid(pairs_for_grid, out_root / "grid_pairs.png", ncols=8)
    print(f"Saved {len(img_paths)} reconstructions to {out_root}")


if __name__ == "__main__":
    main()


